# 10 — Fictional Army: Advanced 2D Matrix Indexing & Coordinate Slicing
> **Interview Prep & Technical Mastery Guide**
> 
> *A comprehensive, battle-tested reference for Python Data Science, Matrix Operations, and Data Manipulation Interviews.*

---

## 📌 Executive Summary & Interview Expectations
This lab is a premier test of **2D slicing mechanics** in Pandas. In technical interviews, interviewers test whether you can navigate a DataFrame as a 2D matrix using both **positional coordinates (`iloc`)** and **label coordinates (`loc`)**, while strictly avoiding chained indexing.

### Core Competencies Tested in this Module:
1. **DataFrame Construction & Indexing**: Ingesting raw nested dictionaries and setting custom row labels without deprecated `inplace=True`.
2. **2D Positional Slicing (`iloc[row_slice, col_slice]`)**: Understanding half-open interval indexing `[start:stop)` across both axes simultaneously.
3. **2D Label Slicing (`loc[row_list, col_list]`)**: Multi-row and multi-column explicit label selection.
4. **Eliminating Chained Indexing**: Replacing bad anti-patterns like `df.loc[row].iloc[col]` with atomic coordinate lookups (`.iat`, `.at`, `.get_loc`).
5. **Interview Corner**: The `inplace=True` deprecation rationale, chained coordinate hazards, and vectorized risk scoring.

## 1. Environment Setup & Data Construction

In [1]:
import numpy as np
import pandas as pd

# Raw dictionary of military data
raw_data = {
    "regiment": ["Nighthawks", "Nighthawks", "Nighthawks", "Nighthawks", "Dragoons", "Dragoons", "Dragoons", "Dragoons", "Scouts", "Scouts", "Scouts", "Scouts"],
    "company": ["1st", "1st", "2nd", "2nd", "1st", "1st", "2nd", "2nd", "1st", "1st", "2nd", "2nd"],
    "deaths": [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
    "battles": [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
    "size": [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
    "veterans": [1, 5, 62, 35, 73, 37, 949, 48, 48, 435, 63, 345],
    "readiness": [1, 2, 3, 3, 2, 3, 2, 3, 2, 3, 1, 1],
    "armored": [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
    "deserters": [4, 24, 31, 2, 3, 4, 18, 3, 2, 3, 2, 3],
    "origin": ["Arizona", "California", "Texas", "Florida", "Maine", "Iowa", "Alaska", "Washington", "Oregon", "Wyoming", "Louisana", "Georgia"]
}

army = pd.DataFrame(data=raw_data)
army.head(4)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,35,3,1,2,Florida

## 2. Setting the Index Idiomatically

### ⚠️ Top Interview Tip: The `inplace=True` Deprecation
- Avoid `army.set_index('origin', inplace=True)`.
- In modern Pandas (and officially across Pandas 2.x and 3.0), `inplace=True` is strongly discouraged and actively being phased out.
- **Idiomatic Standard**: `army = army.set_index('origin')`. It supports method chaining and avoids reference ambiguity.

In [2]:
# Set 'origin' as the index idiomatically
army = army.set_index("origin")
army.head(4)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,35,3,1,2

## 3. Selecting Columns: 1D Series vs 2D Projections

In [3]:
# Single column as Series (using bracket notation)
army["veterans"].head(3)

origin
Arizona        1
California     5
Texas         62
Name: veterans, dtype: int64

In [4]:
# Multiple columns as DataFrame
army[["veterans", "deaths"]].head(3)

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25

In [5]:
# All column names
print("Columns:", list(army.columns))

Columns: ['regiment', 'company', 'deaths', 'battles', 'size', 'veterans', 'readiness', 'armored', 'deserters']

## 4. 2D Matrix Slicing with `.loc` and `.iloc`

In [6]:
# Label coordinates: Select 'deaths', 'size', and 'deserters' from Maine and Alaska
army.loc[["Maine", "Alaska"], ["deaths", "size", "deserters"]]

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         18

In [7]:
# Positional 2D Matrix Slice: Rows 3 to 7 (exclusive) and Columns 3 to 6 (exclusive)
# Corresponds to 0-indexed positions [2:7, 2:6]
army.iloc[2:7, 2:6]

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        35
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

In [8]:
# All rows after the 4th row (index 4 to end)
army.iloc[4:, :].head(4)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,3,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,18
Washington,Dragoons,2nd,62,3,849,48,3,1,3

In [9]:
# Every row up to the 4th row (indices 0, 1, 2, 3)
army.iloc[:4, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,35,3,1,2

In [10]:
# Select 3rd column up to 7th column (positions 2 through 6)
army.iloc[:, 2:7].head(3)

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3

## 5. Boolean Filtering on Armed Forces

In [11]:
# Rows where deaths > 50
army[army["deaths"] > 50].head(4)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,35,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,3,1,4

In [12]:
# Extreme casualty units: deaths > 500 OR deaths < 50
army[(army["deaths"] > 500) | (army["deaths"] < 50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,35,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,18
Louisana,Scouts,2nd,37,8,1099,63,1,1,2
Georgia,Scouts,2nd,35,9,1523,345,1,1,3

In [13]:
# Regiments not named 'Dragoons'
army[army["regiment"] != "Dragoons"].head(4)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,35,3,1,2

In [14]:
# Select specific rows by label
army.loc[["Texas", "Arizona"], :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

## 6. Eliminating Chained Coordinate Indexing

### ⚠️ Top Interview Anti-Pattern: Chained Access
In the original exercise:
```python
# ❌ CHAdeined Access Anti-Pattern:
army.loc[["Arizona"]].iloc[:, 2]      # Double lookup!
army.loc[:, ["deaths"]].iloc[2]       # Creates intermediate DataFrame!
```

**Why this is dangerous in production**:
1. It performs two separate indexing operations, instantiating an intermediate DataFrame in memory.
2. If assigned to, it triggers `SettingWithCopyWarning` or silently fails.
3. **The Solution**: Single atomic coordinate access via `.iloc[i, j]`, `.loc[row, col]`, or `.iat[i, j]`!

In [15]:
# Step 1: Select the 3rd cell in the row named 'Arizona'
# Arizona is at row index 0, 3rd column is index 2 ('deaths')
arizona_row_idx = army.index.get_loc("Arizona")
val_1 = army.iat[arizona_row_idx, 2]
print(f"Value at Arizona, 3rd column (via .iat): {val_1}")

# Step 2: Select the 3rd cell down in the column named 'deaths'
# Row index 2 ('Texas'), column 'deaths'
deaths_col_idx = army.columns.get_loc("deaths")
val_2 = army.iat[2, deaths_col_idx]
print(f"Value at 3rd row, 'deaths' column (via .iat): {val_2}")

Value at Arizona, 3rd column (via .iat): 523
Value at 3rd row, 'deaths' column (via .iat): 25

## 7. 2D Coordinate Slicing Cheat Sheet

| Task | Anti-Pattern | Idiomatic Solution | Benefit |
| :--- | :--- | :--- | :--- |
| **Set Index** | `df.set_index(col, inplace=True)` | `df = df.set_index(col)` | Eliminates deprecated inplace |
| **2D Positional Slice** | Slicing rows then cols | `df.iloc[r_start:r_stop, c_start:c_stop]` | Single atomic memory slice |
| **Label Coordinates** | Chained `.loc[r].iloc[c]` | `df.loc[r_list, c_list]` | Avoids intermediate object |
| **Fast Scalar Coordinate** | `df[c][r]` | `df.iat[i, j]` or `df.at[r, c]` | 10x-20x faster; zero warning |

---
## 🎯 8. Technical Interview Corner: Tricky Questions & Drills

### Q1: Positional vs Label-Based Slicing with Integers
**Question**: If a DataFrame has explicit string labels for columns, but you want to slice the 3rd through 5th columns, how do you do it cleanly?

**Answer**:
Use `.iloc[:, 2:5]`.
The comma separates the axes: `iloc[row_slice, column_slice]`.
Leaving `:` for the row axis means "all rows". `2:5` slices columns at integer positions 2, 3, and 4 (3 columns total).

In [16]:
# Slicing 3rd through 5th columns across all rows
display(army.iloc[:, 2:5].head(3))

            deaths  battles  size
origin
Arizona        523        5  1045
California      52       42   957
Texas           25        2  1099

### Q2: How does `Index.get_loc()` bridge positional and label indexing?
**Question**: How do you dynamically find the integer position of an arbitrary label in an Index?

**Answer**:
Use `df.index.get_loc('label')` or `df.columns.get_loc('col_name')`.
This queries the underlying hash map in $O(1)$ time and returns the exact integer position, allowing you to use high-speed `.iat[i, j]` on label-defined data!

In [17]:
# Bridge label to integer position in O(1)
pos_texas = army.index.get_loc("Texas")
pos_veterans = army.columns.get_loc("veterans")

print(f"'Texas' is at row position:      {pos_texas}")
print(f"'veterans' is at col position:   {pos_veterans}")
print(f"Value via atomic .iat[{pos_texas}, {pos_veterans}]: {army.iat[pos_texas, pos_veterans]}")

'Texas' is at row position:      2
'veterans' is at col position:   5
Value via atomic .iat[2, 5]: 62

### Q3: Advanced Interview Challenge: Regiment Battle Readiness Score
**Challenge**: Compute a normalized `survivability_ratio = (size - deaths) / size` and find which `regiment` has the highest average survivability ratio!

In [18]:
# Solution to Coding Challenge
survivability_by_regiment = (
    army.assign(survivability_ratio=lambda df: (df["size"] - df["deaths"]) / df["size"])
    .groupby("regiment")["survivability_ratio"]
    .mean()
    .sort_values(ascending=False)
    .round(4)
)

print("Average Survivability Ratio by Regiment:")
display(survivability_by_regiment)

Average Survivability Ratio by Regiment:

regiment
Scouts        0.9517
Dragoons      0.7844
Nighthawks    0.7456
Name: survivability_ratio, dtype: float64