# 12 — Hierarchical Indexing: The MultiIndex Object & Multi-Axis Slicing
> **Interview Prep & Technical Mastery Guide**
> 
> *A comprehensive, battle-tested reference for Python Data Science, Quantitative Finance, and Advanced Analytics Interviews.*

---

## 📌 Executive Summary & Interview Expectations
The `pd.MultiIndex` (hierarchical index) allows you to represent multi-dimensional data in a standard 2D tabular format. In technical interviews, MultiIndex questions test whether you understand:
1. **The Architecture of Levels & Codes**: How Pandas represents MultiIndex levels under the hood using integer arrays (codes).
2. **Multi-Level Ingestion**: Ingesting multi-tier headers and multi-column keys (`index_col=[0, 1, 2]`, `header=[0, 1]`).
3. **The Lexicographical Sorting Rule (Lexsort)**: Why unsorted MultiIndices raise `PerformanceWarning` during slicing, and why `sort_index()` is mandatory.
4. **Tuple Indexing vs 2D Indexing**: The critical difference between `df.loc['A', 'B']` (row A, col B) and `df.loc[('A', 'B')]` (multi-level row).
5. **Cross-Sectional Extraction (`.xs()`)**: Slicing an inner level across all outer levels without re-indexing.
6. **The `pd.IndexSlice` Utility**: The production standard for multi-axis hierarchical slicing.

## 1. Environment Setup & MultiIndex Construction from Tuples

In [1]:
import os
import numpy as np
import pandas as pd

# Creating a MultiIndex from Python tuples
address_tuples = [
    ("IL", "Chicago", "Michigan Ave"),
    ("IL", "Chicago", "State St"),
    ("IL", "Evanston", "Sherman Ave"),
    ("NY", "New York", "Broadway"),
    ("NY", "New York", "5th Ave"),
]

row_index = pd.MultiIndex.from_tuples(
    address_tuples, 
    names=["State", "City", "Street"]
)
print("Constructed MultiIndex:")
display(row_index)

Constructed MultiIndex:

MultiIndex([('IL',  'Chicago', 'Michigan Ave'),
            ('IL',  'Chicago',     'State St'),
            ('IL', 'Evanston',  'Sherman Ave'),
            ('NY', 'New York',     'Broadway'),
            ('NY', 'New York',      '5th Ave')],
           names=['State', 'City', 'Street'])

In [2]:
# Creating a MultiIndex DataFrame (hierarchical rows and columns)
col_tuples = [
    ("Culture", "Restaurants"),
    ("Culture", "Museums"),
    ("Services", "Police"),
    ("Services", "Schools")
]
col_index = pd.MultiIndex.from_tuples(col_tuples, names=["Category", "Metric"])

sample_data = [
    ["A", "A+", "B", "A"],
    ["B+", "A", "A-", "B+"],
    ["A-", "B", "A+", "A+"],
    ["A+", "A+", "B-", "A"],
    ["A", "A", "A", "A+"]
]

area_grades = pd.DataFrame(data=sample_data, index=row_index, columns=col_index)
area_grades

Category                        Culture         Services
Metric                      Restaurants Museums   Police Schools
State City     Street
IL    Chicago  Michigan Ave           A      A+        B       A
               State St              B+       A       A-      B+
      Evanston Sherman Ave           A-       B       A+      A+
NY    New York Broadway              A+      A+       B-       A
               5th Ave                A       A        A      A+

## 2. Ingesting Real-World MultiIndex Data: `neighborhoods.csv`

### 💡 Interview Note: `header` and `index_col` as Lists
- `index_col=[0, 1, 2]`: Directs Pandas to turn columns 0, 1, and 2 into a 3-level hierarchical row index.
- `header=[0, 1]`: Directs Pandas to parse the first two lines as a 2-level hierarchical column header.

In [3]:
# Load neighborhoods dataset with 3 row levels and 2 column levels
csv_path = "neighborhoods.csv"
if not os.path.exists(csv_path):
    csv_path = "https://raw.githubusercontent.com/paskhaver/pandas-in-action/master/chapter_07_multiindex_dataFrames/neighborhoods.csv"

neighborhoods = pd.read_csv(
    csv_path,
    index_col=[0, 1, 2],
    header=[0, 1]
)
print("Neighborhoods DataFrame loaded. Shape:", neighborhoods.shape)
neighborhoods.head()

Neighborhoods DataFrame loaded. Shape: (251, 4)

                                             Culture         Services
                                         Restaurants Museums   Police Schools
State City             Street
MO    Fisherborough    244 Tracy View             C+       F       D-      A+
SD    Port Curtisville 446 Cynthia Inlet          C-       B        B      D+
WV    Jimenezview      432 John Common             A      A+        F       B
AK    Stevenshire      238 Andrew Rue             D-       A       A-      A-
ND    New Joshuaport   877 Walter Neck            D+      C-        B       B

## 3. MultiIndex Internals: `names`, `levels`, and `get_level_values()`

### ⚠️ Top Interview Question: How does Pandas store MultiIndex memory?
A `MultiIndex` does not store repeated string labels on every row!
- **`levels`**: Unique labels at each hierarchy tier (e.g. 50 states, 200 cities).
- **`codes`**: An integer array (like `int8` or `int16`) storing pointers to the unique level labels.
This compression makes MultiIndex dramatically more memory-efficient than a denormalized string column!

In [4]:
# Inspect index names and levels
print("Index Names: ", neighborhoods.index.names)
print("Column Names:", neighborhoods.columns.names)
print("Row Level 0 (States):", list(neighborhoods.index.levels[0]))

Index Names:  ['State', 'City', 'Street']
Column Names: [None, None]
Row Level 0 (States): ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']

In [5]:
# Extracting specific level values across all rows
cities_series = neighborhoods.index.get_level_values("City")
print("Total City entries:", len(cities_series))
print("Sample cities:     ", list(cities_series[:5]))

Total City entries: 251
Sample cities:      ['Fisherborough', 'Port Curtisville', 'Jimenezview', 'Stevenshire', 'New Joshuaport']

## 4. Slicing with `.loc`: The Tuple Rule

### ⚠️ Top Interview Trap: Comma vs Tuple in `.loc`
- `df.loc[A, B]`: Selects row `A` and column `B`!
- `df.loc[(A, B)]`: Selects a **hierarchical row** where level 0 is `A` and level 1 is `B`!
Always wrap multi-level row coordinates in **tuples**.

In [6]:
# 1. Select all neighborhoods in Missouri ('MO')
mo_data = neighborhoods.loc["MO"]
mo_data.head(3)

                                      Culture         Services
                                  Restaurants Museums   Police Schools
City           Street
Fisherborough  244 Tracy View              C+       F       D-      A+
East Connie    798 Joseph Orchard           B       D       A+      D+
Port Elizabeth 072 Mariah Creek             C      C-       D-       A

In [7]:
# 2. Select a specific city within a state using a tuple
fisherborough = neighborhoods.loc[("MO", "Fisherborough")]
fisherborough

/var/folders/54/5j97z6452x19yddj6yv2l7j00000gn/T/ipykernel_26740/2637410722.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  fisherborough = neighborhoods.loc[("MO", "Fisherborough")]

                   Culture         Services
               Restaurants Museums   Police Schools
Street
244 Tracy View          C+       F       D-      A+

In [8]:
# 3. Select a specific address across row and column hierarchies
exact_cell = neighborhoods.loc[
    ("MO", "Fisherborough", "244 Tracy View"), 
    ("Culture", "Museums")
]
print(f"Grade for Fisherborough Museums: {exact_cell}")

Grade for Fisherborough Museums: F

## 5. ⚠️ The Lexsort Performance Rule & `sort_index()`

### ⚠️ Top Interview Question: Why must MultiIndex be sorted?
When a MultiIndex is not sorted lexicographically, Pandas cannot use binary search ($O(\log N)$). Instead, it must scan every row ($O(N)$), triggering:
`PerformanceWarning: indexing past lexsort depth may impact performance`.
**Golden Rule**: Always call `df = df.sort_index()` after creating or reshaping a MultiIndex DataFrame!

In [9]:
# Check if index is sorted
print("Is row index lexicographically sorted?", neighborhoods.index.is_monotonic_increasing)

# Sort index across all levels
neighborhoods = neighborhoods.sort_index()
print("After sort_index(), is monotonic?", neighborhoods.index.is_monotonic_increasing)
neighborhoods.head(4)

Is row index lexicographically sorted? False
After sort_index(), is monotonic? True

                                             Culture         Services
                                         Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove             C-      A-       A+       C
      Scottstad      082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D
      Stevenshire    238 Andrew Rue               D-       A       A-      A-

## 6. Cross-Sectional Extraction: `.xs()`

### 💡 Interview Pro-Tip — Why use `.xs()`?
Selecting an inner-level label across all outer levels is awkward with `.loc`.
The `.xs()` (cross-section) method allows you to directly target **any level** without knowing or specifying the parent levels!

In [10]:
# Extract all data for a specific City ('Fisherborough') across all States
city_xs = neighborhoods.xs(key="Fisherborough", level="City", axis=0)
display(city_xs)

                         Culture         Services
                     Restaurants Museums   Police Schools
State Street
IN    975 Bell Fork           C+      B+        C      A+
MO    244 Tracy View          C+       F       D-      A+

In [11]:
# Cross-section on column hierarchy: Extract 'Police' grades across all categories
police_xs = neighborhoods.xs(key="Police", level=1, axis=1)
display(police_xs.head(4))

                                         Services
State City           Street
AK    Rowlandchester 386 Rebecca Cove          A+
      Scottstad      082 Leblanc Freeway        D
                     114 Jones Garden           D
      Stevenshire    238 Andrew Rue            A-

## 7. Advanced Multi-Axis Slicing with `pd.IndexSlice`

`pd.IndexSlice` is the cleanest, most pythonic tool for slicing arbitrary levels across both rows and columns.

In [12]:
# Using pd.IndexSlice
idx = pd.IndexSlice

# Select all streets in states 'AK' through 'AZ', and only Culture metrics
slice_result = neighborhoods.loc[
    idx["AK":"AZ", :, :], 
    idx["Culture", :]
]
slice_result.head(5)

                                             Culture
                                         Restaurants Museums
State City           Street
AK    Rowlandchester 386 Rebecca Cove             C-      A-
      Scottstad      082 Leblanc Freeway           D      C-
                     114 Jones Garden             D-      D-
      Stevenshire    238 Andrew Rue               D-       A
AL    Clarkland      430 Douglas Mission           A       F

## 8. Level Manipulation: `swaplevel()`, `stack()`, and `unstack()`

In [13]:
# Swap City and State levels
swapped = neighborhoods.swaplevel("State", "City")
swapped.head(3)

                                             Culture         Services
                                         Restaurants Museums   Police Schools
City           State Street
Rowlandchester AK    386 Rebecca Cove             C-      A-       A+       C
Scottstad      AK    082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D

In [14]:
# Unstack: move inner row level ('Street') into columns
unstacked = neighborhoods.head(2).unstack(level="Street")
print("Unstacked DataFrame shape:", unstacked.shape)

Unstacked DataFrame shape: (2, 8)

## 9. MultiIndex Cheat Sheet

| Task | Idiomatic Syntax | Key Trap / Benefit |
| :--- | :--- | :--- |
| **Ingest Multi-Header** | `pd.read_csv(..., header=[0, 1])` | Header levels defined by list of row indices |
| **Ingest Multi-Index** | `pd.read_csv(..., index_col=[0, 1, 2])` | Assigns multi-tier row index |
| **Lexsort Requirement** | `df.sort_index()` | Eliminates `PerformanceWarning` and enables $O(\log N)$ lookup |
| **Tuple Row Lookup** | `df.loc[(lvl0, lvl1)]` | Comma without tuple slices columns instead! |
| **Inner-Level Slicing** | `df.xs(key, level='Name', axis=0)` | Eliminates need to specify parent levels |
| **Multi-Axis Slicing** | `df.loc[idx[...], idx[...]]` | Uses `idx = pd.IndexSlice` |

---
## 🎯 10. Technical Interview Corner: Tricky Questions & Drills

### Q1: The `PerformanceWarning` on Unsorted MultiIndex
**Question**: An interviewer asks: *"You attempt to slice a MultiIndex DataFrame with `.loc['CA':'NY']` and Pandas raises a `PerformanceWarning: indexing past lexsort depth may impact performance`. Why did this happen and how do you resolve it?"*

**Answer**:
1. **Root Cause**: The MultiIndex levels are not sorted in lexicographical order (`is_monotonic_increasing == False`). To find values in an unsorted hierarchy, Pandas cannot use binary search; it is forced to do a slow full-table scan.
2. **Resolution**: Call `df = df.sort_index()`. This organizes the internal B-tree index, eliminating the warning and speeding up queries by up to 100x.

In [15]:
# Demonstration of sort_index requirement
unsorted_idx = pd.MultiIndex.from_tuples([("B", 2), ("A", 1), ("B", 1)])
unsorted_df = pd.DataFrame({"Val": [10, 20, 30]}, index=unsorted_idx)

print("Before sort_index is_monotonic_increasing:", unsorted_df.index.is_monotonic_increasing)
sorted_df = unsorted_df.sort_index()
print("After sort_index is_monotonic_increasing: ", sorted_df.index.is_monotonic_increasing)
display(sorted_df)

Before sort_index is_monotonic_increasing: False
After sort_index is_monotonic_increasing:  True

     Val
A 1   20
B 1   30
  2   10

### Q2: Row vs Column Ambiguity in `.loc`
**Question**: What is the difference between `df.loc['A', 'B']` and `df.loc[('A', 'B'), :]`?

**Answer**:
- `df.loc['A', 'B']`: Selects row label `'A'` and column label `'B'`.
- `df.loc[('A', 'B'), :]`: Selects the row where outer level is `'A'` and inner level is `'B'`, across all columns.

### Q3: Advanced Interview Challenge: Top Restaurant States
**Challenge**: In a single chained expression, find the top 3 States with the highest number of `'A+'` grades in `('Culture', 'Restaurants')`!

In [16]:
# Solution to Coding Challenge using MultiIndex selection and level aggregation
rest_ratings = neighborhoods[("Culture", "Restaurants")]

top_restaurant_states = (
    rest_ratings[rest_ratings == "A+"]
    .groupby("State")
    .count()
    .sort_values(ascending=False)
    .head(3)
)

print("Top 3 States with highest 'A+' Restaurant ratings:")
display(top_restaurant_states)

Top 3 States with highest 'A+' Restaurant ratings:

State
IN    2
PA    2
CT    1
Name: (Culture, Restaurants), dtype: int64